name: CI-Linux

on:
  push:
    branches:
      - master

jobs:
  build-n-run-tests:

    runs-on: self-hosted
    
    steps:
    - name: Pull, Build, and Run Tests
      run: 
        echo $(pwd) | ts
        git clone https://github.com/simo-andreev/Emotion &&/
        pwd &&/
        echo user- ${{ inputs.username }}
