name: CI-Linux

on:
  push:
    branches:
      - master

jobs:
  build-n-run-tests:

    runs-on: self-hosted
    
    steps:
    - name: Pull, Build, and Run Tests
      run: |
        echo work dir- $(pwd)
        echo user- $(whoami)
        echo displays- $(xrandr -q)
        git fetch
        git pull
        dotnet publish Tests -c DebugUnix64 -r linux-x64 -o Tests/bin/linux --self-contained true
        cd ./Tests/bin/linux
        ./Tests
